// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GM3aBsH3NlEWmngHZQupTPo31gPvoQE',
    appId: '1:672198876204:web:da989e1558ac6bcccf4589',
    messagingSenderId: '672198876204',
    projectId: 'plant-app-3c0f3',
    authDomain: 'plant-app-3c0f3.firebaseapp.com',
    storageBucket: 'plant-app-3c0f3.appspot.com',
    measurementId: 'G-T61C69K351',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJd6IjjPOE-4yM7yr2ZfHQKFxpAxkpXTs',
    appId: '1:672198876204:android:9ae411ac638c3767cf4589',
    messagingSenderId: '672198876204',
    projectId: 'plant-app-3c0f3',
    storageBucket: 'plant-app-3c0f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRXdp-_hNGi521Myas9B1lVGtJLf14lU',
    appId: '1:672198876204:ios:82b2025ca6ca241ccf4589',
    messagingSenderId: '672198876204',
    projectId: 'plant-app-3c0f3',
    storageBucket: 'plant-app-3c0f3.appspot.com',
    iosBundleId: 'com.example.plantsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRXdp-_hNGi521Myas9B1lVGtJLf14lU',
    appId: '1:672198876204:ios:82b2025ca6ca241ccf4589',
    messagingSenderId: '672198876204',
    projectId: 'plant-app-3c0f3',
    storageBucket: 'plant-app-3c0f3.appspot.com',
    iosBundleId: 'com.example.plantsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9GM3aBsH3NlEWmngHZQupTPo31gPvoQE',
    appId: '1:672198876204:web:8fa9ead03a2ab17bcf4589',
    messagingSenderId: '672198876204',
    projectId: 'plant-app-3c0f3',
    authDomain: 'plant-app-3c0f3.firebaseapp.com',
    storageBucket: 'plant-app-3c0f3.appspot.com',
    measurementId: 'G-18H69Y8SGR',
  );
}
