name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  dio: ^5.7.0
  file_picker: ^8.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\Group 44.png
  - assets\Group 46.png
  - assets\Group.png
  - assets\g1520.png
  - assets\Frame 4.png
  - assets\Facebook_f_logo_(2019) 1.png
  - assets\Vector.png
  - assets\Group 57@2x.png
  - assets\Vector@2x.png
  - assets\Vector@3x.png
  - assets\Group 58@2x.png
  - assets\Group 61@2x.png
  - assets\Vector (2).png

