name: advance_todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  riverpod: ^2.5.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
